server:
  port: ${sp.ai}
  servlet:
    # 设置应用上下文路径
    context-path: /ai
spring:
  application:
    name: ${sn.ai}
  ai:
    # 配置DashScope模型
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          # 模型类型，如：qwen-max、qwen-turbo、qwen-plus
          model: glm-5.2
          # 核采样温度, 取值范围[0.0,1.0]，越小越模型越严谨、保守、确定, 越大模型越有创造力、越活泼、越容易天马行空
          temperature: 0.7
          # 限制大模型单次回答你时最多能吐出多少个字（1000个Token在中文里大约相当于600-800个汉字）
          max_tokens: 6000
          # 核采样, 用来过滤掉那些太离谱、太奇怪的词, 取值范围[0.0,1.0], 为1表示不限制，所有的词都参与备选，越小模型越死板严谨
          top_p: 0.9
    # 配置MCP客户端
    mcp:
      client:
        enabled: true
        name: my-mcp-client  # 客户端名称，需根据业务自行修改
        version: 1.0.0
        type: SYNC
    alibaba:
      # 配置MCP
      mcp:
        nacos:
          # 配置MCP Nacos客户端
          client:
            enabled: true  # 是否启用，必须配置否则找不到工具
            # sse、streamable、configs 等配置需根据实际业务需求补充和完善
            streamable:
              connections:
                server1:
                  service-name: mcp-nacos-gateway
                  version: 1.0.0
            configs:
              server1:
                namespace: his-dev
                server-addr: ${spring.cloud.nacos.server-addr}
                username: ${spring.cloud.nacos.username}
                password: ${spring.cloud.nacos.password}
      # 配置A2A模型
      a2a:
        nacos:
          server-addr: ${spring.cloud.nacos.server-addr}
          username: ${spring.cloud.nacos.username}
          password: ${spring.cloud.nacos.password}
          namespace: his-dev
          discovery:
            # 启用服务发现（查询其他 Agent）
            enabled: true