spring:
  cloud:
    #nacos配置
    #https://github.com/alibaba/spring-cloud-alibaba/blob/2025.0.x/spring-cloud-alibaba-examples/nacos-example/readme-zh.md
    nacos:
      server-addr: 39.99.114.126:8848
      username: nacos
      password: 123456
      discovery:
        namespace: 1653f775-4782-46ad-9cd2-b60155a574c6
      config:
        namespace: 1653f775-4782-46ad-9cd2-b60155a574c6

#日志级别
#logging:
#  level:
#    root: debug


#开启MP SQL日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl